name: Codex Task
description: A well-scoped task for ChatGPT Codex to implement
title: "[Codex] <short summary>"
labels: ["codex"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: One clear outcome Codex should deliver.
    validations: { required: true }
  - type: textarea
    id: context
    attributes:
      label: Context / Pointers
      description: Files, functions, stack traces, links.
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How we know the task is done.
    validations: { required: true }
  - type: checkboxes
    id: constraints
    attributes:
      label: Constraints
      options:
        - label: Don’t change public APIs unless necessary
        - label: Keep all user strings in English
        - label: Add/Update tests for new logic
  - type: input
    id: branch
    attributes:
      label: Branch name
      placeholder: feat/<slug>
