name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: |
          if [ -f codex-constraints.txt ]; then
            python -m pip install -r requirements.txt -c codex-constraints.txt
          else
            python -m pip install -r requirements.txt
          fi
          python -m pip install flake8 pytest pytest-asyncio
      - run: flake8 app tests
      - run: pytest -q
